# name: Prepare for Docker Build
# description: Set up Docker Build dependencies (without pushing)

# inputs:
#   image:
#     description: Image name
#     required: true
#   tag:
#     description: Docker tag to use
#     required: true
#   is_ingestion:
#     description: true if we are building an Ingestion image, false otherwise
#     required: true
#     default: "false"
#   release_version:
#     description: OpenMetadata Release Version

# outputs:
#   tags:
#     description: Generated Docker Tags
#     value: ${{ steps.meta.outputs.tags }}

# runs:
#   using: composite
#   steps:
#     - name: Set up QEMU
#       uses: docker/setup-qemu-action@v3

#     - name: Set up Docker Buildx
#       uses: docker/setup-buildx-action@v3



name: Prepare for Docker Build
description: Set up Docker Build dependencies (without pushing) and run Maven build

inputs:
  image:
    description: Image name
    required: true
  tag:
    description: Docker tag to use
    required: true
  is_ingestion:
    description: true if we are building an Ingestion image, false otherwise
    required: true
    default: "false"
  release_version:
    description: OpenMetadata Release Version

outputs:
  tags:
    description: Generated Docker Tags
    value: ${{ steps.meta.outputs.tags }}

runs:
  using: composite
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
          java-version: 17
          distribution: 'temurin'

    - name: Install antlr cli
      shell: bash
      run: |
          sudo make install_antlr_cli

    - name: Setup jq
      shell: bash
      run: |
          sudo apt-get update
          sudo apt-get install jq

    - name: Build OpenMetadata Server Application
      shell: bash
      run: |
          mvn -DskipTests clean package

    - name: Upload OpenMetadata application to Artifact
      uses: actions/upload-artifact@v4
      with:
          name: openmetadata-binary
          path: /home/runner/work/OpenMetadata/OpenMetadata/openmetadata-dist/target/*.tar.gz