name: Prepare for Docker Build
description: Set up Docker Build dependencies (without pushing)

inputs:
  image:
    description: Image name
    required: true
  tag:
    description: Docker tag to use
    required: true
  is_ingestion:
    description: true if we are building an Ingestion image, false otherwise
    required: true
    default: "false"
  release_version:
    description: OpenMetadata Release Version

outputs:
  tags:
    description: Generated Docker Tags
    value: ${{ steps.meta.outputs.tags }}

runs:
  using: composite
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3