name: Prepare for Docker Build
description: Set up Docker Build dependencies (without pushing)

inputs:
  image:
    description: Image name
    required: true
  tag:
    description: Docker tag to use
    required: true
  is_ingestion:
    description: true if we are building an Ingestion image, false otherwise
    required: true
    default: "false"
  release_version:
    description: OpenMetadata Release Version

outputs:
  tags:
    description: Generated Docker Tags
    value: ${{ steps.meta.outputs.tags }}

runs:
  using: composite
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build OpenMetadata Artifacts (Maven)
      shell: bash
      run: |
        set -e  
        mvn clean install -DskipTests  

    # - name: Install Ubuntu dependencies (Only for ingestion images)
    #   if: inputs.is_ingestion == 'true'
    #   shell: bash
    #   run: |
    #     sudo apt-get install -y python3-venv

    # - name: Install open-metadata dependencies (Only for ingestion images)
    #   if: inputs.is_ingestion == 'true'
    #   shell: bash
    #   run: |
    #     python3 -m venv env
    #     source env/bin/activate
    #     pip install --upgrade pip
    #     sudo make install_antlr_cli
    #     make install_dev generate
    
    # - name: Docker Meta (Generate Tags)
    #   id: meta
    #   uses: docker/metadata-action@v5
    #   with:
    #     images: |
    #       ${{ inputs.image }}
    #     sep-tags: ','
    #     tags: |
    #       type=raw,value=${{ inputs.release_version }},enable=${{ inputs.is_ingestion == 'true' }}
    #       type=raw,${{ inputs.tag }}