name: Docker Build and Trivy Scan

on:
  pull_request:

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write 

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
    
      - name: Prepare for Docker Build
        id: prepare
        uses: ./.github/actions/prepare-for-docker-build
        with:
          image: openmetadata/server
          tag: trivy

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
  
      - name: Install antlr cli
        run: |
          sudo make install_antlr_cli
  
      - name: Setup jq
        run: |
          sudo apt-get update
          sudo apt-get install jq
  
      - name: Build OpenMetadata Server Application
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mvn -DskipTests clean package
  
      - name: Upload OpenMetadata application to Artifact
        uses: actions/upload-artifact@v4
        with:
          name: openmetadata-binary
          path: /home/runner/work/OpenMetadata/OpenMetadata/openmetadata-dist/target/*.tar.gz

      - name: Build Docker Image
        run: |
          docker build -t openmetadata/server:trivy -f docker/development/Dockerfile .
    
      - name: Run Trivy Image Scan
        id: trivy_scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "image"
          image-ref: "openmetadata/server:trivy"
          ignore-unfixed: true
          severity: "HIGH,CRITICAL"
          output: "trivy-results.txt" 

      - name: Format Trivy Output
        run: |
          echo "## 🚨 Trivy Security Scan Results 🚨" > trivy-results.md
          echo "" >> trivy-results.md
          if [[ -s trivy-results.txt ]]; then
            echo "### 🔴 Found HIGH and CRITICAL vulnerabilities:" >> trivy-results.md
            echo '```' >> trivy-results.md
            cat trivy-results.txt >> trivy-results.md
            echo '```' >> trivy-results.md
          else
            echo "✅ No HIGH or CRITICAL vulnerabilities found." >> trivy-results.md
          fi 

      - name: Comment Trivy Scan Results on PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: trivy-results.md