name: Docker Build and Trivy Scan

on:
  pull_request:

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write 

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
            docker build -t openmetadata/server:latest -f ./docker/development/ .
 
      - name: Run Trivy Image Scan
        id: trivy_scan
        uses: aquasecurity/trivy-action@master
        with:
            scan-type: "image"
            image-ref: "openmetadata/server:latest"
            ignore-unfixed: true
            severity: "HIGH,CRITICAL"
            output: "trivy-results.txt" 
      
      - name: Format Trivy Output
        run: |
          echo "## 🚨 Trivy Security Scan Results 🚨" > trivy-results.md
          echo "" >> trivy-results.md
          if [[ -s trivy-results.txt ]]; then
            echo "### 🔴 Found HIGH and CRITICAL vulnerabilities:" >> trivy-results.md
            echo '```' >> trivy-results.md
            cat trivy-results.txt >> trivy-results.md
            echo '```' >> trivy-results.md
          else
            echo "✅ No HIGH or CRITICAL vulnerabilities found." >> trivy-results.md
          fi 

      - name: Comment Trivy Scan Results on PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: trivy-results.md
        

